pool:
  vmImage: 'ubuntu-20.04'

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '5.0.203'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'
